In [5]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
coimbra = pd.read_csv('dataR2_coimbra.csv')
coimbra

,Age,BMI,Glucose,Insulin,HOMA,Leptin,Adiponectin,Resistin,MCP.1,Classification
0,48,23.500000,70,2.707,0.467409,8.8071,9.702400,7.99585,417.114,1
1,83,20.690495,92,3.115,0.706897,8.8438,5.429285,4.06405,468.786,1
2,82,23.124670,91,4.498,1.009651,17.9393,22.432040,9.27715,554.697,1
3,68,21.367521,77,3.226,0.612725,9.8827,7.169560,12.76600,928.220,1
4,86,21.111111,92,3.549,0.805386,6.6994,4.819240,10.57635,773.920,1
...,...,...,...,...,...,...,...,...,...,...
111,45,26.850000,92,3.330,0.755688,54.6800,12.100000,10.96000,268.230,2
112,62,26.840000,100,4.530,1.117400,12.4500,21.420000,7.32000,330.160,2
113,65,32.050000,97,5.730,1.370998,61.4800,22.540000,10.33000,314.050,2
114,72,25.590000,82,2.820,0.570392,24.9600,33.750000,3.27000,392.460,2
115,86,27.180000,138,19.910,6.777364,90.2800,14.110000,4.35000,90.090,2

In [27]:
c_patient = coimbra.loc[coimbra['Classification'] == 2]
c_control = coimbra.loc[coimbra['Classification'] == 1]
c_patient

,Age,BMI,Glucose,Insulin,HOMA,Leptin,Adiponectin,Resistin,MCP.1,Classification
52,45,21.303949,102,13.852,3.485163,7.6476,21.056625,23.03408,552.444,2
53,45,20.829995,74,4.560,0.832352,7.7529,8.237405,28.03230,382.955,2
54,49,20.956608,94,12.305,2.853119,11.2406,8.412175,23.11770,573.630,2
55,34,24.242424,92,21.699,4.924226,16.7353,21.823745,12.06534,481.949,2
56,42,21.359915,93,2.999,0.687971,19.0826,8.462915,17.37615,321.919,2
...,...,...,...,...,...,...,...,...,...,...
111,45,26.850000,92,3.330,0.755688,54.6800,12.100000,10.96000,268.230,2
112,62,26.840000,100,4.530,1.117400,12.4500,21.420000,7.32000,330.160,2
113,65,32.050000,97,5.730,1.370998,61.4800,22.540000,10.33000,314.050,2
114,72,25.590000,82,2.820,0.570392,24.9600,33.750000,3.27000,392.460,2
115,86,27.180000,138,19.910,6.777364,90.2800,14.110000,4.35000,90.090,2

In [28]:
# group control table by age, take means
c_c_age = c_control.groupby(['Age']).mean()

c_c_age.reset_index(inplace=True)

c_c_age.drop(labels='Classification', axis=1, inplace=True)

c_c_age.index.names=['ID']

c_c_age = c_c_age.round(3)

# group patient table by age, take means
c_age = c_patient.groupby(['Age']).mean()

c_age.reset_index(inplace=True)

c_age.drop(labels='Classification', axis=1, inplace=True)

c_age.index.names=['ID']

c_age = c_age.round(3)

# export tables to csv files
c_c_age.to_csv('coimbra_control_age_means.csv')

c_age.to_csv('coimbra_patient_age_means.csv')
c_age

,Age,BMI,Glucose,Insulin,HOMA,Leptin,Adiponectin,Resistin,MCP.1
ID,,,,,,,,,
0,34,24.242,92.000,21.699,4.924,16.735,21.824,12.065,481.949
1,38,22.500,95.000,5.261,1.233,8.438,4.772,15.736,199.055
2,40,29.236,115.500,22.163,6.923,22.680,6.472,21.784,465.692
3,41,26.673,97.000,22.033,5.272,44.706,13.495,27.832,783.796
4,42,25.328,95.500,3.585,0.848,15.672,7.579,35.524,681.881
5,43,28.906,102.000,7.442,1.865,17.791,9.570,27.377,791.023
6,44,24.063,106.333,27.853,7.334,14.639,13.983,10.988,290.872
7,45,23.628,94.333,5.800,1.384,19.929,11.500,15.114,422.893
8,46,25.407,88.667,15.370,3.294,13.907,12.490,9.377,274.133
9,48,30.612,129.333,14.460,4.512,26.580,11.965,26.633,1378.305
10,49,26.141,94.000,12.057,3.259,27.826,8.456,18.149,642.545
11,51,20.132,100.333,4.378,1.086,9.573,9.306,6.778,321.164
12,52,30.801,87.000,30.212,6.483,29.274,6.269,24.246,764.667
13,54,30.134,102.500,7.820,2.144,48.979,5.858,7.702,426.664
14,55,31.975,92.000,16.635,3.775,37.223,11.018,7.165,483.377
15,57,34.838,95.000,12.548,2.940,33.161,2.365,9.954,655.834
16,58,29.155,139.000,16.582,5.685,22.888,10.263,13.974,923.886
17,59,25.753,87.500,5.025,1.132,15.963,10.335,19.948,632.900
18,60,31.231,131.000,30.130,9.736,37.843,8.404,11.500,396.021
19,62,24.748,96.000,4.006,0.954,11.157,16.328,9.008,517.066
20,64,22.222,98.000,5.700,1.378,12.190,4.784,13.912,395.976
21,65,30.877,93.000,10.290,2.318,44.006,11.178,16.754,803.046
22,66,26.562,89.000,6.524,1.432,14.908,8.430,14.919,269.487
23,68,28.321,116.500,7.175,2.097,13.785,10.237,8.966,323.600
24,69,24.979,110.000,7.746,2.096,23.664,4.713,16.092,533.404
25,71,26.713,108.000,14.298,3.770,36.282,3.571,45.993,527.950
26,72,26.115,90.000,6.063,1.319,24.516,18.132,7.620,273.473
27,73,37.109,134.000,5.636,1.863,41.406,3.336,6.892,788.902
28,74,28.650,88.000,3.012,0.654,31.123,7.652,18.356,572.401
29,75,30.480,152.000,7.010,2.628,50.530,10.060,11.730,99.450
30,81,31.640,100.000,9.669,2.385,38.807,10.637,29.558,426.175
31,82,31.217,100.000,18.077,4.459,31.645,9.924,19.947,994.316
32,85,27.689,196.000,51.814,25.050,70.882,7.902,55.215,1078.359
33,86,26.923,169.500,30.760,13.704,68.964,9.734,14.360,894.265

In [29]:
c_c_age

,Age,BMI,Glucose,Insulin,HOMA,Leptin,Adiponectin,Resistin,MCP.1
ID,,,,,,,,,
0,24,18.670,88.000,6.107,1.330,8.880,36.060,6.850,632.220
1,25,22.860,82.000,4.090,0.827,20.450,23.670,5.140,313.730
2,28,35.856,87.000,8.576,1.840,68.510,4.794,21.444,358.624
3,29,27.640,83.000,5.736,1.175,40.605,16.465,14.592,539.890
4,32,36.513,87.000,14.026,3.010,49.373,5.100,17.102,588.460
5,34,26.723,82.500,4.000,0.820,21.660,10.376,6.273,463.692
6,35,32.764,87.000,5.597,1.210,44.911,8.008,19.237,700.862
7,36,31.376,83.000,5.467,1.111,12.703,6.833,12.438,557.768
8,38,23.340,75.000,5.782,1.070,15.260,17.950,9.350,165.020
9,43,34.422,89.000,23.194,5.092,31.213,8.301,6.710,960.246
10,44,20.760,86.000,7.553,1.600,14.090,20.320,7.640,63.610
11,45,37.036,83.000,6.760,1.384,39.980,4.617,8.704,586.173
12,47,22.030,84.000,2.869,0.590,26.650,38.040,3.320,191.720
13,48,23.500,70.000,2.707,0.467,8.807,9.702,7.996,417.114
14,49,22.854,92.000,3.226,0.732,6.832,13.680,10.318,530.410
15,50,38.579,106.000,6.703,1.753,46.640,4.668,11.784,887.160
16,51,27.689,77.000,3.855,0.732,20.092,3.192,10.375,473.859
17,53,36.790,101.000,10.175,2.535,27.184,20.030,10.263,695.754
18,54,30.483,90.000,5.537,1.229,12.331,9.731,10.193,1227.910
19,60,26.349,103.000,5.138,1.305,24.300,2.194,20.254,378.996
20,61,32.039,85.000,18.077,3.790,30.773,7.780,13.684,444.395
21,64,34.530,95.000,4.427,1.037,21.212,5.463,6.702,252.449
22,66,31.649,90.750,8.750,2.027,40.435,7.453,13.925,706.890
23,67,29.607,79.000,5.819,1.134,21.903,2.194,4.208,585.307
24,68,21.368,77.000,3.226,0.613,9.883,7.170,12.766,928.220
25,69,32.331,94.333,7.260,1.667,47.966,8.957,32.806,249.803
26,71,30.300,102.000,8.340,2.098,56.502,8.130,4.299,200.976
27,73,22.000,97.000,3.350,0.802,4.470,10.359,6.284,136.855
28,75,25.333,87.333,6.076,1.326,31.148,8.107,6.388,286.832
29,76,26.830,101.250,13.032,3.340,22.636,8.726,7.514,350.638
30,77,30.744,80.500,4.230,0.844,17.763,8.939,14.518,553.550
31,78,25.300,60.000,3.508,0.519,6.633,10.567,4.664,209.749
32,82,23.125,91.000,4.498,1.010,17.939,22.432,9.277,554.697
33,83,20.690,92.000,3.115,0.707,8.844,5.429,4.064,468.786
34,85,26.600,96.000,4.462,1.057,7.850,7.932,9.614,232.006
35,86,21.111,92.000,3.549,0.805,6.699,4.819,10.576,773.920
36,89,22.700,77.000,4.690,0.891,6.964,5.590,12.936,1256.083