In [1]:
import pandas as pd
import sqlalchemy
from sqlalchemy import create_engine
import psycopg2

In [2]:
dataframe = pd.read_csv("dataset_13_breast-cancer.csv")

In [3]:
dataframe.head()

,age,menopause,tumor-size,inv-nodes,node-caps,deg-malig,breast,breast-quad,irradiat,Class
0,'40-49','premeno','15-19','0-2','yes','3','right','left_up','no','recurrence-events'
1,'50-59','ge40','15-19','0-2','no','1','right','central','no','no-recurrence-events'
2,'50-59','ge40','35-39','0-2','no','2','left','left_low','no','recurrence-events'
3,'40-49','premeno','35-39','0-2','yes','3','right','left_low','yes','no-recurrence-events'
4,'40-49','premeno','30-34','3-5','yes','2','left','right_up','no','recurrence-events'

In [4]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 286 entries, 0 to 285
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   age          286 non-null    object
 1   menopause    286 non-null    object
 2   tumor-size   286 non-null    object
 3   inv-nodes    286 non-null    object
 4   node-caps    286 non-null    object
 5   deg-malig    286 non-null    object
 6   breast       286 non-null    object
 7   breast-quad  286 non-null    object
 8   irradiat     286 non-null    object
 9   Class        286 non-null    object
dtypes: object(10)
memory usage: 22.5+ KB

In [5]:
 dataframe.drop(columns=['deg-malig'])  


# C:\Program Files\PostgreSQL\11\bin\

,age,menopause,tumor-size,inv-nodes,node-caps,breast,breast-quad,irradiat,Class
0,'40-49','premeno','15-19','0-2','yes','right','left_up','no','recurrence-events'
1,'50-59','ge40','15-19','0-2','no','right','central','no','no-recurrence-events'
2,'50-59','ge40','35-39','0-2','no','left','left_low','no','recurrence-events'
3,'40-49','premeno','35-39','0-2','yes','right','left_low','yes','no-recurrence-events'
4,'40-49','premeno','30-34','3-5','yes','left','right_up','no','recurrence-events'
...,...,...,...,...,...,...,...,...,...
281,'50-59','ge40','30-34','6-8','yes','left','left_low','no','no-recurrence-events'
282,'50-59','premeno','25-29','3-5','yes','left','left_low','yes','no-recurrence-events'
283,'30-39','premeno','30-34','6-8','yes','right','right_up','no','no-recurrence-events'
284,'50-59','premeno','15-19','0-2','no','right','left_low','no','no-recurrence-events'
285,'50-59','ge40','40-44','0-2','no','left','right_up','no','no-recurrence-events'

In [6]:
conn_string = 'postgresql://postgres:postgres@localhost:5432/Breast_cancer'
# conn_string = 'postgresql://scott:tiger@localhost:5432/mydatabase'